# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BusinessAddress(BaseModel):
    """
    Serializer for BusinessAddress model. Used for merchant and shipping addresses.
    """ # noqa: E501
    id: StrictInt
    address: StrictStr
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    city_name: Annotated[str, Field(strict=True, max_length=32)]
    state_name: Annotated[str, Field(strict=True, max_length=32)]
    district_id: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    district_name: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    longitude: Optional[Annotated[str, Field(strict=True)]] = None
    latitude: Optional[Annotated[str, Field(strict=True)]] = None
    building_number: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    unit: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    receiver_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    receiver_phone: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    is_accurate: Optional[StrictBool] = None
    is_active: Optional[StrictBool] = None
    created_at: datetime
    modified_at: datetime
    __properties: ClassVar[List[str]] = ["id", "address", "postal_code", "city_name", "state_name", "district_id", "district_name", "longitude", "latitude", "building_number", "unit", "receiver_name", "receiver_phone", "is_accurate", "is_active", "created_at", "modified_at"]

    @field_validator('longitude')
    def longitude_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d{0,6}(?:\.\d{0,16})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,6}(?:\.\d{0,16})?$/")
        return value

    @field_validator('latitude')
    def latitude_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d{0,6}(?:\.\d{0,16})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,6}(?:\.\d{0,16})?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BusinessAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "modified_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postal_code'] = None

        # set to None if district_id (nullable) is None
        # and model_fields_set contains the field
        if self.district_id is None and "district_id" in self.model_fields_set:
            _dict['district_id'] = None

        # set to None if district_name (nullable) is None
        # and model_fields_set contains the field
        if self.district_name is None and "district_name" in self.model_fields_set:
            _dict['district_name'] = None

        # set to None if longitude (nullable) is None
        # and model_fields_set contains the field
        if self.longitude is None and "longitude" in self.model_fields_set:
            _dict['longitude'] = None

        # set to None if latitude (nullable) is None
        # and model_fields_set contains the field
        if self.latitude is None and "latitude" in self.model_fields_set:
            _dict['latitude'] = None

        # set to None if building_number (nullable) is None
        # and model_fields_set contains the field
        if self.building_number is None and "building_number" in self.model_fields_set:
            _dict['building_number'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if receiver_name (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_name is None and "receiver_name" in self.model_fields_set:
            _dict['receiver_name'] = None

        # set to None if receiver_phone (nullable) is None
        # and model_fields_set contains the field
        if self.receiver_phone is None and "receiver_phone" in self.model_fields_set:
            _dict['receiver_phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BusinessAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "address": obj.get("address"),
            "postal_code": obj.get("postal_code"),
            "city_name": obj.get("city_name"),
            "state_name": obj.get("state_name"),
            "district_id": obj.get("district_id"),
            "district_name": obj.get("district_name"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude"),
            "building_number": obj.get("building_number"),
            "unit": obj.get("unit"),
            "receiver_name": obj.get("receiver_name"),
            "receiver_phone": obj.get("receiver_phone"),
            "is_accurate": obj.get("is_accurate"),
            "is_active": obj.get("is_active"),
            "created_at": obj.get("created_at"),
            "modified_at": obj.get("modified_at")
        })
        return _obj


