# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GatewayTypeEnum(int, Enum):
    """
    * `1` - آنلاین * `2` - BNPL (الان بخر، بعداً پرداخت کن) * `3` - اعتباری * `4` - کیف پول دیجی‌پی * `5` - اقساط پیش‌فرض
    """

    """
    allowed enum values
    """
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GatewayTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


