# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from bwdk_sdk.models.merchant import Merchant
from bwdk_sdk.models.order_item_create import OrderItemCreate
from bwdk_sdk.models.order_status_enum import OrderStatusEnum
from bwdk_sdk.models.order_user import OrderUser
from bwdk_sdk.models.packing import Packing
from bwdk_sdk.models.payment_order import PaymentOrder
from bwdk_sdk.models.shipping_method import ShippingMethod
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderDetail(BaseModel):
    """
    OrderDetail
    """ # noqa: E501
    id: StrictInt
    created_at: datetime
    order_uuid: UUID
    reservation_expired_at: Optional[StrictInt] = Field(description="Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است")
    merchant_order_id: StrictStr = Field(description="شناسه منحصر به فرد سفارش در سیستم فروشنده")
    status: OrderStatusEnum
    status_display: StrictStr
    main_amount: StrictInt = Field(description="مجموع قیمت اولیه تمام کالاهای سفارش بدون تخفیف (به تومان)")
    final_amount: StrictInt = Field(description="قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)")
    total_paid_amount: StrictInt = Field(description="مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)")
    discount_amount: StrictInt = Field(description="مبلغ کل تخفیف اعمال شده بر سفارش (به تومان)")
    tax_amount: StrictInt = Field(description="مبلغ کل مالیات برای سفارش (به تومان)")
    shipping_amount: StrictInt = Field(description="هزینه ارسال برای سفارش (به تومان)")
    loyalty_amount: StrictInt = Field(description="مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان)")
    callback_url: StrictStr = Field(description="آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش")
    merchant: Merchant
    items: List[OrderItemCreate]
    source_address: Optional[Any]
    destination_address: Optional[Any]
    selected_shipping_method: ShippingMethod
    shipping_selected_at: Optional[datetime]
    address_selected_at: Optional[datetime]
    packing_amount: StrictInt = Field(description="هزینه روش بسته‌بندی انتخاب‌شده (به تومان)")
    packing_selected_at: Optional[datetime]
    selected_packing: Packing
    can_select_packing: StrictBool
    can_select_shipping: StrictBool
    can_select_address: StrictBool
    can_proceed_to_payment: StrictBool
    is_paid: StrictBool
    user: OrderUser
    payment: PaymentOrder
    preparation_time: StrictInt = Field(description="Preparation time for the order (in days)")
    weight: Union[StrictFloat, StrictInt] = Field(description="Total weight of the order (in grams)")
    selected_shipping_data: Dict[str, Any]
    reference_code: StrictStr = Field(description="کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)")
    promotion_discount_amount: Union[StrictFloat, StrictInt]
    promotion_data: Dict[str, Any]
    digipay_markup_amount: StrictInt = Field(description="Markup amount for the order (in Tomans)")
    markup_commission_percentage: StrictInt = Field(description="Markup commission percentage for the order (in percent)")
    previous_status: Optional[OrderStatusEnum]
    previous_status_display: StrictStr
    __properties: ClassVar[List[str]] = ["id", "created_at", "order_uuid", "reservation_expired_at", "merchant_order_id", "status", "status_display", "main_amount", "final_amount", "total_paid_amount", "discount_amount", "tax_amount", "shipping_amount", "loyalty_amount", "callback_url", "merchant", "items", "source_address", "destination_address", "selected_shipping_method", "shipping_selected_at", "address_selected_at", "packing_amount", "packing_selected_at", "selected_packing", "can_select_packing", "can_select_shipping", "can_select_address", "can_proceed_to_payment", "is_paid", "user", "payment", "preparation_time", "weight", "selected_shipping_data", "reference_code", "promotion_discount_amount", "promotion_data", "digipay_markup_amount", "markup_commission_percentage", "previous_status", "previous_status_display"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "order_uuid",
            "reservation_expired_at",
            "merchant_order_id",
            "status",
            "status_display",
            "main_amount",
            "final_amount",
            "total_paid_amount",
            "discount_amount",
            "tax_amount",
            "shipping_amount",
            "loyalty_amount",
            "callback_url",
            "source_address",
            "destination_address",
            "selected_shipping_method",
            "shipping_selected_at",
            "address_selected_at",
            "packing_amount",
            "packing_selected_at",
            "selected_packing",
            "can_select_packing",
            "can_select_shipping",
            "can_select_address",
            "can_proceed_to_payment",
            "is_paid",
            "user",
            "payment",
            "preparation_time",
            "weight",
            "selected_shipping_data",
            "reference_code",
            "promotion_discount_amount",
            "promotion_data",
            "digipay_markup_amount",
            "markup_commission_percentage",
            "previous_status",
            "previous_status_display",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of merchant
        if self.merchant:
            _dict['merchant'] = self.merchant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of selected_shipping_method
        if self.selected_shipping_method:
            _dict['selected_shipping_method'] = self.selected_shipping_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of selected_packing
        if self.selected_packing:
            _dict['selected_packing'] = self.selected_packing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['payment'] = self.payment.to_dict()
        # set to None if reservation_expired_at (nullable) is None
        # and model_fields_set contains the field
        if self.reservation_expired_at is None and "reservation_expired_at" in self.model_fields_set:
            _dict['reservation_expired_at'] = None

        # set to None if source_address (nullable) is None
        # and model_fields_set contains the field
        if self.source_address is None and "source_address" in self.model_fields_set:
            _dict['source_address'] = None

        # set to None if destination_address (nullable) is None
        # and model_fields_set contains the field
        if self.destination_address is None and "destination_address" in self.model_fields_set:
            _dict['destination_address'] = None

        # set to None if shipping_selected_at (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_selected_at is None and "shipping_selected_at" in self.model_fields_set:
            _dict['shipping_selected_at'] = None

        # set to None if address_selected_at (nullable) is None
        # and model_fields_set contains the field
        if self.address_selected_at is None and "address_selected_at" in self.model_fields_set:
            _dict['address_selected_at'] = None

        # set to None if packing_selected_at (nullable) is None
        # and model_fields_set contains the field
        if self.packing_selected_at is None and "packing_selected_at" in self.model_fields_set:
            _dict['packing_selected_at'] = None

        # set to None if previous_status (nullable) is None
        # and model_fields_set contains the field
        if self.previous_status is None and "previous_status" in self.model_fields_set:
            _dict['previous_status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "order_uuid": obj.get("order_uuid"),
            "reservation_expired_at": obj.get("reservation_expired_at"),
            "merchant_order_id": obj.get("merchant_order_id"),
            "status": obj.get("status"),
            "status_display": obj.get("status_display"),
            "main_amount": obj.get("main_amount"),
            "final_amount": obj.get("final_amount"),
            "total_paid_amount": obj.get("total_paid_amount"),
            "discount_amount": obj.get("discount_amount"),
            "tax_amount": obj.get("tax_amount"),
            "shipping_amount": obj.get("shipping_amount"),
            "loyalty_amount": obj.get("loyalty_amount"),
            "callback_url": obj.get("callback_url"),
            "merchant": Merchant.from_dict(obj["merchant"]) if obj.get("merchant") is not None else None,
            "items": [OrderItemCreate.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "source_address": obj.get("source_address"),
            "destination_address": obj.get("destination_address"),
            "selected_shipping_method": ShippingMethod.from_dict(obj["selected_shipping_method"]) if obj.get("selected_shipping_method") is not None else None,
            "shipping_selected_at": obj.get("shipping_selected_at"),
            "address_selected_at": obj.get("address_selected_at"),
            "packing_amount": obj.get("packing_amount"),
            "packing_selected_at": obj.get("packing_selected_at"),
            "selected_packing": Packing.from_dict(obj["selected_packing"]) if obj.get("selected_packing") is not None else None,
            "can_select_packing": obj.get("can_select_packing"),
            "can_select_shipping": obj.get("can_select_shipping"),
            "can_select_address": obj.get("can_select_address"),
            "can_proceed_to_payment": obj.get("can_proceed_to_payment"),
            "is_paid": obj.get("is_paid"),
            "user": OrderUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "payment": PaymentOrder.from_dict(obj["payment"]) if obj.get("payment") is not None else None,
            "preparation_time": obj.get("preparation_time"),
            "weight": obj.get("weight"),
            "selected_shipping_data": obj.get("selected_shipping_data"),
            "reference_code": obj.get("reference_code"),
            "promotion_discount_amount": obj.get("promotion_discount_amount"),
            "promotion_data": obj.get("promotion_data"),
            "digipay_markup_amount": obj.get("digipay_markup_amount"),
            "markup_commission_percentage": obj.get("markup_commission_percentage"),
            "previous_status": obj.get("previous_status"),
            "previous_status_display": obj.get("previous_status_display")
        })
        return _obj


