# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from bwdk_sdk.models.order_item_create import OrderItemCreate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderCreate(BaseModel):
    """
    OrderCreate
    """ # noqa: E501
    merchant_order_id: Annotated[str, Field(strict=True, max_length=64)] = Field(description="شناسه منحصر به فرد این سفارش در سیستم فروشنده")
    merchant_unique_id: Annotated[str, Field(strict=True, max_length=64)] = Field(description="شناسه منحصر به فرد برای تأیید اصالت سفارش")
    main_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)")
    final_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)")
    total_paid_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)")
    discount_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مبلغ کل تخفیف برای تمام سفارش (به تومان)")
    tax_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مبلغ کل مالیات برای تمام سفارش (به تومان)")
    shipping_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="هزینه ارسال برای سفارش (به تومان)")
    loyalty_amount: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)")
    callback_url: Annotated[str, Field(strict=True, max_length=256)] = Field(description="آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت")
    destination_address: Optional[Any]
    items: List[OrderItemCreate]
    merchant: Optional[StrictInt] = Field(default=None, description="مقدار توسط سیستم جایگذاری می شود")
    source_address: Optional[Any] = Field(default=None, description="مقدار توسط سیستم جایگذاری می شود")
    user: Optional[StrictInt]
    reservation_expired_at: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش")
    reference_code: StrictStr = Field(description="کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)")
    preparation_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=2, description="Preparation time for the order (in days)")
    weight: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Total Weight of the order (in grams)")
    __properties: ClassVar[List[str]] = ["merchant_order_id", "merchant_unique_id", "main_amount", "final_amount", "total_paid_amount", "discount_amount", "tax_amount", "shipping_amount", "loyalty_amount", "callback_url", "destination_address", "items", "merchant", "source_address", "user", "reservation_expired_at", "reference_code", "preparation_time", "weight"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "destination_address",
            "user",
            "reference_code",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # set to None if destination_address (nullable) is None
        # and model_fields_set contains the field
        if self.destination_address is None and "destination_address" in self.model_fields_set:
            _dict['destination_address'] = None

        # set to None if source_address (nullable) is None
        # and model_fields_set contains the field
        if self.source_address is None and "source_address" in self.model_fields_set:
            _dict['source_address'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if reservation_expired_at (nullable) is None
        # and model_fields_set contains the field
        if self.reservation_expired_at is None and "reservation_expired_at" in self.model_fields_set:
            _dict['reservation_expired_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_order_id": obj.get("merchant_order_id"),
            "merchant_unique_id": obj.get("merchant_unique_id"),
            "main_amount": obj.get("main_amount"),
            "final_amount": obj.get("final_amount"),
            "total_paid_amount": obj.get("total_paid_amount"),
            "discount_amount": obj.get("discount_amount"),
            "tax_amount": obj.get("tax_amount"),
            "shipping_amount": obj.get("shipping_amount"),
            "loyalty_amount": obj.get("loyalty_amount"),
            "callback_url": obj.get("callback_url"),
            "destination_address": obj.get("destination_address"),
            "items": [OrderItemCreate.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "merchant": obj.get("merchant"),
            "source_address": obj.get("source_address"),
            "user": obj.get("user"),
            "reservation_expired_at": obj.get("reservation_expired_at"),
            "reference_code": obj.get("reference_code"),
            "preparation_time": obj.get("preparation_time") if obj.get("preparation_time") is not None else 2,
            "weight": obj.get("weight")
        })
        return _obj


