# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bwdk_sdk.models.gateway_type_enum import GatewayTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentOrder(BaseModel):
    """
    PaymentOrder
    """ # noqa: E501
    final_amount: StrictInt
    gateway_type: GatewayTypeEnum
    gateway_type_display: StrictStr
    paid_at: StrictStr
    gateway_name: Optional[StrictStr]
    invoice_id: Optional[StrictStr]
    settlement_date: StrictStr
    settlement_status: StrictInt
    settlement_status_display: StrictStr
    __properties: ClassVar[List[str]] = ["final_amount", "gateway_type", "gateway_type_display", "paid_at", "gateway_name", "invoice_id", "settlement_date", "settlement_status", "settlement_status_display"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "final_amount",
            "gateway_type",
            "gateway_type_display",
            "paid_at",
            "gateway_name",
            "invoice_id",
            "settlement_date",
            "settlement_status",
            "settlement_status_display",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gateway_name (nullable) is None
        # and model_fields_set contains the field
        if self.gateway_name is None and "gateway_name" in self.model_fields_set:
            _dict['gateway_name'] = None

        # set to None if invoice_id (nullable) is None
        # and model_fields_set contains the field
        if self.invoice_id is None and "invoice_id" in self.model_fields_set:
            _dict['invoice_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "final_amount": obj.get("final_amount"),
            "gateway_type": obj.get("gateway_type"),
            "gateway_type_display": obj.get("gateway_type_display"),
            "paid_at": obj.get("paid_at"),
            "gateway_name": obj.get("gateway_name"),
            "invoice_id": obj.get("invoice_id"),
            "settlement_date": obj.get("settlement_date"),
            "settlement_status": obj.get("settlement_status"),
            "settlement_status_display": obj.get("settlement_status_display")
        })
        return _obj


