# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from bwdk_sdk.models.business_address import BusinessAddress
from bwdk_sdk.models.delivery_time_range_display import DeliveryTimeRangeDisplay
from bwdk_sdk.models.shipping_type_enum import ShippingTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ShippingMethod(BaseModel):
    """
    Serializer for shipping method details.
    """ # noqa: E501
    id: StrictInt
    name: Annotated[str, Field(strict=True, max_length=64)] = Field(description="نام روش ارسال")
    description: Optional[StrictStr] = Field(default=None, description="توضیحات روش ارسال و جزئیات تحویل آن")
    shipping_type: Optional[ShippingTypeEnum] = Field(default=None, description="نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس")
    get_shipping_type_display: StrictStr
    shipping_type_display: StrictStr
    cost: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان")
    secondary_cost: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(default=None, description="هزینه ارسال برای مناطق دیگر به تومان")
    minimum_time_sending: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = Field(default=None, description="حداقل تعداد روزها از تاریخ سفارش تا تحویل")
    maximum_time_sending: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = Field(default=None, description="حداکثر تعداد روزها از تاریخ سفارش تا تحویل")
    delivery_time_display: StrictStr
    delivery_time_range_display: DeliveryTimeRangeDisplay
    inventory_address: BusinessAddress
    is_pay_at_destination: Optional[StrictBool] = Field(default=None, description="Whether the shipping method is pay at destination")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "shipping_type", "get_shipping_type_display", "shipping_type_display", "cost", "secondary_cost", "minimum_time_sending", "maximum_time_sending", "delivery_time_display", "delivery_time_range_display", "inventory_address", "is_pay_at_destination"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShippingMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "get_shipping_type_display",
            "shipping_type_display",
            "delivery_time_display",
            "delivery_time_range_display",
            "inventory_address",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delivery_time_range_display
        if self.delivery_time_range_display:
            _dict['delivery_time_range_display'] = self.delivery_time_range_display.to_dict()
        # override the default output from pydantic by calling `to_dict()` of inventory_address
        if self.inventory_address:
            _dict['inventory_address'] = self.inventory_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShippingMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "shipping_type": obj.get("shipping_type"),
            "get_shipping_type_display": obj.get("get_shipping_type_display"),
            "shipping_type_display": obj.get("shipping_type_display"),
            "cost": obj.get("cost"),
            "secondary_cost": obj.get("secondary_cost"),
            "minimum_time_sending": obj.get("minimum_time_sending"),
            "maximum_time_sending": obj.get("maximum_time_sending"),
            "delivery_time_display": obj.get("delivery_time_display"),
            "delivery_time_range_display": DeliveryTimeRangeDisplay.from_dict(obj["delivery_time_range_display"]) if obj.get("delivery_time_range_display") is not None else None,
            "inventory_address": BusinessAddress.from_dict(obj["inventory_address"]) if obj.get("inventory_address") is not None else None,
            "is_pay_at_destination": obj.get("is_pay_at_destination")
        })
        return _obj


