# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.api.merchant_orders_api import MerchantOrdersApi


class TestMerchantOrdersApi(unittest.TestCase):
    """MerchantOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MerchantOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_order_api_v1_create_order_create(self) -> None:
        """Test case for order_api_v1_create_order_create

        ساخت سفارش
        """
        pass

    def test_order_api_v1_manager_list(self) -> None:
        """Test case for order_api_v1_manager_list

        لیست سفارشات
        """
        pass

    def test_order_api_v1_manager_paid_list(self) -> None:
        """Test case for order_api_v1_manager_paid_list

        سفارش پرداخت‌شده و تایید‌نشده
        """
        pass

    def test_order_api_v1_manager_refund_create(self) -> None:
        """Test case for order_api_v1_manager_refund_create

        بازگشت سفارش
        """
        pass

    def test_order_api_v1_manager_retrieve(self) -> None:
        """Test case for order_api_v1_manager_retrieve

        دریافت سفارش
        """
        pass

    def test_order_api_v1_manager_update_status_update(self) -> None:
        """Test case for order_api_v1_manager_update_status_update

        Update Order Status
        """
        pass

    def test_order_api_v1_manager_verify_create(self) -> None:
        """Test case for order_api_v1_manager_verify_create

        تایید سفارش
        """
        pass


if __name__ == '__main__':
    unittest.main()
