# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.order_create import OrderCreate

class TestOrderCreate(unittest.TestCase):
    """OrderCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCreate:
        """Test OrderCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCreate`
        """
        model = OrderCreate()
        if include_optional:
            return OrderCreate(
                merchant_order_id = '',
                merchant_unique_id = '',
                main_amount = 0,
                final_amount = 0,
                total_paid_amount = 0,
                discount_amount = 0,
                tax_amount = 0,
                shipping_amount = 0,
                loyalty_amount = 0,
                callback_url = '',
                destination_address = None,
                items = [
                    bwdk_sdk.models.order_item_create.OrderItemCreate(
                        name = '', 
                        primary_amount = 0, 
                        amount = 0, 
                        count = 0, 
                        discount_amount = 0, 
                        tax_amount = 0, 
                        image_link = '', 
                        options = [
                            bwdk_sdk.models.option.Option(
                                type_name = null, 
                                name = '', 
                                value = '', 
                                is_color = True, )
                            ], 
                        preparation_time = 0, 
                        weight = 0, )
                    ],
                merchant = 56,
                source_address = None,
                user = 56,
                reservation_expired_at = 0,
                reference_code = '',
                preparation_time = 0,
                weight = 0
            )
        else:
            return OrderCreate(
                merchant_order_id = '',
                merchant_unique_id = '',
                callback_url = '',
                destination_address = None,
                items = [
                    bwdk_sdk.models.order_item_create.OrderItemCreate(
                        name = '', 
                        primary_amount = 0, 
                        amount = 0, 
                        count = 0, 
                        discount_amount = 0, 
                        tax_amount = 0, 
                        image_link = '', 
                        options = [
                            bwdk_sdk.models.option.Option(
                                type_name = null, 
                                name = '', 
                                value = '', 
                                is_color = True, )
                            ], 
                        preparation_time = 0, 
                        weight = 0, )
                    ],
                user = 56,
                reference_code = '',
        )
        """

    def testOrderCreate(self):
        """Test OrderCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
