# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.order_item_create import OrderItemCreate

class TestOrderItemCreate(unittest.TestCase):
    """OrderItemCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderItemCreate:
        """Test OrderItemCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderItemCreate`
        """
        model = OrderItemCreate()
        if include_optional:
            return OrderItemCreate(
                name = '',
                primary_amount = 0,
                amount = 0,
                count = 0,
                discount_amount = 0,
                tax_amount = 0,
                image_link = '',
                options = [
                    bwdk_sdk.models.option.Option(
                        type_name = null, 
                        name = '', 
                        value = '', 
                        is_color = True, )
                    ],
                preparation_time = 0,
                weight = 0
            )
        else:
            return OrderItemCreate(
                name = '',
                count = 0,
                options = [
                    bwdk_sdk.models.option.Option(
                        type_name = null, 
                        name = '', 
                        value = '', 
                        is_color = True, )
                    ],
        )
        """

    def testOrderItemCreate(self):
        """Test OrderItemCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
