# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.delivery_time_range_display import DeliveryTimeRangeDisplay

class TestDeliveryTimeRangeDisplay(unittest.TestCase):
    """DeliveryTimeRangeDisplay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryTimeRangeDisplay:
        """Test DeliveryTimeRangeDisplay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryTimeRangeDisplay`
        """
        model = DeliveryTimeRangeDisplay()
        if include_optional:
            return DeliveryTimeRangeDisplay(
                min_date = '',
                max_date = ''
            )
        else:
            return DeliveryTimeRangeDisplay(
                min_date = '',
                max_date = '',
        )
        """

    def testDeliveryTimeRangeDisplay(self):
        """Test DeliveryTimeRangeDisplay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
