# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.api.order_shipping_api import OrderShippingApi


class TestOrderShippingApi(unittest.TestCase):
    """OrderShippingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderShippingApi()

    def tearDown(self) -> None:
        pass

    def test_order_api_v1_manager_cancel_shipment_create(self) -> None:
        """Test case for order_api_v1_manager_cancel_shipment_create

        Cancel Shipment
        """
        pass

    def test_order_api_v1_manager_change_shipping_method_update(self) -> None:
        """Test case for order_api_v1_manager_change_shipping_method_update

        Change Shipping Method
        """
        pass

    def test_order_api_v1_manager_revive_shipment_create(self) -> None:
        """Test case for order_api_v1_manager_revive_shipment_create

        Revive Shipment
        """
        pass


if __name__ == '__main__':
    unittest.main()
