# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.shipping_method import ShippingMethod

class TestShippingMethod(unittest.TestCase):
    """ShippingMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShippingMethod:
        """Test ShippingMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShippingMethod`
        """
        model = ShippingMethod()
        if include_optional:
            return ShippingMethod(
                id = 56,
                name = '',
                description = '',
                shipping_type = 1,
                get_shipping_type_display = '',
                shipping_type_display = '',
                cost = 0,
                secondary_cost = 0,
                minimum_time_sending = 0,
                maximum_time_sending = 0,
                delivery_time_display = '',
                delivery_time_range_display = bwdk_sdk.models.delivery_time_range_display.DeliveryTimeRangeDisplay(
                    min_date = '', 
                    max_date = '', ),
                inventory_address = bwdk_sdk.models.business_address.BusinessAddress(
                    id = 56, 
                    address = '', 
                    postal_code = '', 
                    city_name = '', 
                    state_name = '', 
                    district_id = 0, 
                    district_name = '', 
                    longitude = '-807', 
                    latitude = '-807', 
                    building_number = '', 
                    unit = '', 
                    receiver_name = '', 
                    receiver_phone = '', 
                    is_accurate = True, 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                is_pay_at_destination = True
            )
        else:
            return ShippingMethod(
                id = 56,
                name = '',
                get_shipping_type_display = '',
                shipping_type_display = '',
                delivery_time_display = '',
                delivery_time_range_display = bwdk_sdk.models.delivery_time_range_display.DeliveryTimeRangeDisplay(
                    min_date = '', 
                    max_date = '', ),
                inventory_address = bwdk_sdk.models.business_address.BusinessAddress(
                    id = 56, 
                    address = '', 
                    postal_code = '', 
                    city_name = '', 
                    state_name = '', 
                    district_id = 0, 
                    district_name = '', 
                    longitude = '-807', 
                    latitude = '-807', 
                    building_number = '', 
                    unit = '', 
                    receiver_name = '', 
                    receiver_phone = '', 
                    is_accurate = True, 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testShippingMethod(self):
        """Test ShippingMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
