# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.type_name_enum import TypeNameEnum

class TestTypeNameEnum(unittest.TestCase):
    """TypeNameEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeNameEnum(self):
        """Test TypeNameEnum"""
        # inst = TypeNameEnum()

if __name__ == '__main__':
    unittest.main()
