# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.api.seller_profile_management_api import SellerProfileManagementApi


class TestSellerProfileManagementApi(unittest.TestCase):
    """SellerProfileManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SellerProfileManagementApi()

    def tearDown(self) -> None:
        pass

    def test_merchant_api_v1_auth_status_retrieve(self) -> None:
        """Test case for merchant_api_v1_auth_status_retrieve

        وضعیت لاگین بودن
        """
        pass


if __name__ == '__main__':
    unittest.main()
