# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.merchant_order_revive_shipment_response import MerchantOrderReviveShipmentResponse

class TestMerchantOrderReviveShipmentResponse(unittest.TestCase):
    """MerchantOrderReviveShipmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantOrderReviveShipmentResponse:
        """Test MerchantOrderReviveShipmentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantOrderReviveShipmentResponse`
        """
        model = MerchantOrderReviveShipmentResponse()
        if include_optional:
            return MerchantOrderReviveShipmentResponse(
                message = '',
                order_uuid = '',
                status = 1,
                status_display = ''
            )
        else:
            return MerchantOrderReviveShipmentResponse(
                message = '',
                order_uuid = '',
                status = 1,
                status_display = '',
        )
        """

    def testMerchantOrderReviveShipmentResponse(self):
        """Test MerchantOrderReviveShipmentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
