# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.merchant_order_cancel_shipment_response import MerchantOrderCancelShipmentResponse

class TestMerchantOrderCancelShipmentResponse(unittest.TestCase):
    """MerchantOrderCancelShipmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantOrderCancelShipmentResponse:
        """Test MerchantOrderCancelShipmentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantOrderCancelShipmentResponse`
        """
        model = MerchantOrderCancelShipmentResponse()
        if include_optional:
            return MerchantOrderCancelShipmentResponse(
                message = '',
                order_uuid = '',
                status = 1,
                status_display = ''
            )
        else:
            return MerchantOrderCancelShipmentResponse(
                message = '',
                order_uuid = '',
                status = 1,
                status_display = '',
        )
        """

    def testMerchantOrderCancelShipmentResponse(self):
        """Test MerchantOrderCancelShipmentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
