# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.paginated_merchant_paid_order_list_list import PaginatedMerchantPaidOrderListList

class TestPaginatedMerchantPaidOrderListList(unittest.TestCase):
    """PaginatedMerchantPaidOrderListList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedMerchantPaidOrderListList:
        """Test PaginatedMerchantPaidOrderListList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedMerchantPaidOrderListList`
        """
        model = PaginatedMerchantPaidOrderListList()
        if include_optional:
            return PaginatedMerchantPaidOrderListList(
                next = 'http://api.example.org/accounts/?cursor=cD00ODY%3D"',
                previous = 'http://api.example.org/accounts/?cursor=cj0xJnA9NDg3',
                results = [
                    bwdk_sdk.models.merchant_paid_order_list.MerchantPaidOrderList(
                        order_uuid = '', 
                        merchant_order_id = '', 
                        merchant_unique_id = '', 
                        paid_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        refunds_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PaginatedMerchantPaidOrderListList(
                results = [
                    bwdk_sdk.models.merchant_paid_order_list.MerchantPaidOrderList(
                        order_uuid = '', 
                        merchant_order_id = '', 
                        merchant_unique_id = '', 
                        paid_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        refunds_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPaginatedMerchantPaidOrderListList(self):
        """Test PaginatedMerchantPaidOrderListList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
