# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.paginated_order_detail_list import PaginatedOrderDetailList

class TestPaginatedOrderDetailList(unittest.TestCase):
    """PaginatedOrderDetailList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedOrderDetailList:
        """Test PaginatedOrderDetailList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedOrderDetailList`
        """
        model = PaginatedOrderDetailList()
        if include_optional:
            return PaginatedOrderDetailList(
                next = 'http://api.example.org/accounts/?cursor=cD00ODY%3D"',
                previous = 'http://api.example.org/accounts/?cursor=cj0xJnA9NDg3',
                results = [
                    bwdk_sdk.models.order_detail.OrderDetail(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        order_uuid = '', 
                        reservation_expired_at = 56, 
                        merchant_order_id = '', 
                        status = null, 
                        status_display = '', 
                        main_amount = 56, 
                        final_amount = 56, 
                        total_paid_amount = 56, 
                        discount_amount = 56, 
                        tax_amount = 56, 
                        shipping_amount = 56, 
                        loyalty_amount = 56, 
                        callback_url = '', 
                        merchant = bwdk_sdk.models.merchant.Merchant(
                            name = '', 
                            domain = '', 
                            logo = '', ), 
                        items = [
                            bwdk_sdk.models.order_item_create.OrderItemCreate(
                                name = '', 
                                primary_amount = 0, 
                                amount = 0, 
                                count = 0, 
                                discount_amount = 0, 
                                tax_amount = 0, 
                                image_link = '', 
                                options = [
                                    bwdk_sdk.models.option.Option(
                                        type_name = null, 
                                        name = '', 
                                        value = '', 
                                        is_color = True, )
                                    ], 
                                preparation_time = 0, 
                                weight = 0, )
                            ], 
                        source_address = null, 
                        destination_address = null, 
                        selected_shipping_method = null, 
                        shipping_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        address_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        packing_amount = 56, 
                        packing_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        selected_packing = null, 
                        can_select_packing = True, 
                        can_select_shipping = True, 
                        can_select_address = True, 
                        can_proceed_to_payment = True, 
                        is_paid = True, 
                        user = null, 
                        payment = null, 
                        preparation_time = 56, 
                        weight = 1.337, 
                        selected_shipping_data = {
                            'key' : null
                            }, 
                        reference_code = '', 
                        promotion_discount_amount = 1.337, 
                        promotion_data = {
                            'key' : null
                            }, 
                        digipay_markup_amount = 56, 
                        markup_commission_percentage = 56, 
                        previous_status = null, 
                        previous_status_display = '', )
                    ]
            )
        else:
            return PaginatedOrderDetailList(
                results = [
                    bwdk_sdk.models.order_detail.OrderDetail(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        order_uuid = '', 
                        reservation_expired_at = 56, 
                        merchant_order_id = '', 
                        status = null, 
                        status_display = '', 
                        main_amount = 56, 
                        final_amount = 56, 
                        total_paid_amount = 56, 
                        discount_amount = 56, 
                        tax_amount = 56, 
                        shipping_amount = 56, 
                        loyalty_amount = 56, 
                        callback_url = '', 
                        merchant = bwdk_sdk.models.merchant.Merchant(
                            name = '', 
                            domain = '', 
                            logo = '', ), 
                        items = [
                            bwdk_sdk.models.order_item_create.OrderItemCreate(
                                name = '', 
                                primary_amount = 0, 
                                amount = 0, 
                                count = 0, 
                                discount_amount = 0, 
                                tax_amount = 0, 
                                image_link = '', 
                                options = [
                                    bwdk_sdk.models.option.Option(
                                        type_name = null, 
                                        name = '', 
                                        value = '', 
                                        is_color = True, )
                                    ], 
                                preparation_time = 0, 
                                weight = 0, )
                            ], 
                        source_address = null, 
                        destination_address = null, 
                        selected_shipping_method = null, 
                        shipping_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        address_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        packing_amount = 56, 
                        packing_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        selected_packing = null, 
                        can_select_packing = True, 
                        can_select_shipping = True, 
                        can_select_address = True, 
                        can_proceed_to_payment = True, 
                        is_paid = True, 
                        user = null, 
                        payment = null, 
                        preparation_time = 56, 
                        weight = 1.337, 
                        selected_shipping_data = {
                            'key' : null
                            }, 
                        reference_code = '', 
                        promotion_discount_amount = 1.337, 
                        promotion_data = {
                            'key' : null
                            }, 
                        digipay_markup_amount = 56, 
                        markup_commission_percentage = 56, 
                        previous_status = null, 
                        previous_status_display = '', )
                    ],
        )
        """

    def testPaginatedOrderDetailList(self):
        """Test PaginatedOrderDetailList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
