# coding: utf-8

"""
    BWDK API

    <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bwdk_sdk.models.order_detail import OrderDetail

class TestOrderDetail(unittest.TestCase):
    """OrderDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderDetail:
        """Test OrderDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderDetail`
        """
        model = OrderDetail()
        if include_optional:
            return OrderDetail(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                order_uuid = '',
                reservation_expired_at = 56,
                merchant_order_id = '',
                status = 1,
                status_display = '',
                main_amount = 56,
                final_amount = 56,
                total_paid_amount = 56,
                discount_amount = 56,
                tax_amount = 56,
                shipping_amount = 56,
                loyalty_amount = 56,
                callback_url = '',
                merchant = bwdk_sdk.models.merchant.Merchant(
                    name = '', 
                    domain = '', 
                    logo = '', ),
                items = [
                    bwdk_sdk.models.order_item_create.OrderItemCreate(
                        name = '', 
                        primary_amount = 0, 
                        amount = 0, 
                        count = 0, 
                        discount_amount = 0, 
                        tax_amount = 0, 
                        image_link = '', 
                        options = [
                            bwdk_sdk.models.option.Option(
                                type_name = null, 
                                name = '', 
                                value = '', 
                                is_color = True, )
                            ], 
                        preparation_time = 0, 
                        weight = 0, )
                    ],
                source_address = None,
                destination_address = None,
                selected_shipping_method = bwdk_sdk.models.shipping_method.ShippingMethod(
                    id = 56, 
                    name = '', 
                    description = '', 
                    shipping_type = null, 
                    get_shipping_type_display = '', 
                    shipping_type_display = '', 
                    cost = 0, 
                    secondary_cost = 0, 
                    minimum_time_sending = 0, 
                    maximum_time_sending = 0, 
                    delivery_time_display = '', 
                    delivery_time_range_display = null, 
                    inventory_address = null, 
                    is_pay_at_destination = True, ),
                shipping_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                address_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                packing_amount = 56,
                packing_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                selected_packing = bwdk_sdk.models.packing.Packing(
                    id = 56, 
                    name = '', 
                    price = 0, ),
                can_select_packing = True,
                can_select_shipping = True,
                can_select_address = True,
                can_proceed_to_payment = True,
                is_paid = True,
                user = bwdk_sdk.models.order_user.OrderUser(
                    first_name = '', 
                    last_name = '', 
                    phone_number = '', 
                    national_identity_number = '', 
                    birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                payment = bwdk_sdk.models.payment_order.PaymentOrder(
                    final_amount = 56, 
                    gateway_type = null, 
                    gateway_type_display = '', 
                    paid_at = '', 
                    gateway_name = '', 
                    invoice_id = '', 
                    settlement_date = '', 
                    settlement_status = 56, 
                    settlement_status_display = '', ),
                preparation_time = 56,
                weight = 1.337,
                selected_shipping_data = {
                    'key' : null
                    },
                reference_code = '',
                promotion_discount_amount = 1.337,
                promotion_data = {
                    'key' : null
                    },
                digipay_markup_amount = 56,
                markup_commission_percentage = 56,
                previous_status = 1,
                previous_status_display = ''
            )
        else:
            return OrderDetail(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                order_uuid = '',
                reservation_expired_at = 56,
                merchant_order_id = '',
                status = 1,
                status_display = '',
                main_amount = 56,
                final_amount = 56,
                total_paid_amount = 56,
                discount_amount = 56,
                tax_amount = 56,
                shipping_amount = 56,
                loyalty_amount = 56,
                callback_url = '',
                merchant = bwdk_sdk.models.merchant.Merchant(
                    name = '', 
                    domain = '', 
                    logo = '', ),
                items = [
                    bwdk_sdk.models.order_item_create.OrderItemCreate(
                        name = '', 
                        primary_amount = 0, 
                        amount = 0, 
                        count = 0, 
                        discount_amount = 0, 
                        tax_amount = 0, 
                        image_link = '', 
                        options = [
                            bwdk_sdk.models.option.Option(
                                type_name = null, 
                                name = '', 
                                value = '', 
                                is_color = True, )
                            ], 
                        preparation_time = 0, 
                        weight = 0, )
                    ],
                source_address = None,
                destination_address = None,
                selected_shipping_method = bwdk_sdk.models.shipping_method.ShippingMethod(
                    id = 56, 
                    name = '', 
                    description = '', 
                    shipping_type = null, 
                    get_shipping_type_display = '', 
                    shipping_type_display = '', 
                    cost = 0, 
                    secondary_cost = 0, 
                    minimum_time_sending = 0, 
                    maximum_time_sending = 0, 
                    delivery_time_display = '', 
                    delivery_time_range_display = null, 
                    inventory_address = null, 
                    is_pay_at_destination = True, ),
                shipping_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                address_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                packing_amount = 56,
                packing_selected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                selected_packing = bwdk_sdk.models.packing.Packing(
                    id = 56, 
                    name = '', 
                    price = 0, ),
                can_select_packing = True,
                can_select_shipping = True,
                can_select_address = True,
                can_proceed_to_payment = True,
                is_paid = True,
                user = bwdk_sdk.models.order_user.OrderUser(
                    first_name = '', 
                    last_name = '', 
                    phone_number = '', 
                    national_identity_number = '', 
                    birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                payment = bwdk_sdk.models.payment_order.PaymentOrder(
                    final_amount = 56, 
                    gateway_type = null, 
                    gateway_type_display = '', 
                    paid_at = '', 
                    gateway_name = '', 
                    invoice_id = '', 
                    settlement_date = '', 
                    settlement_status = 56, 
                    settlement_status_display = '', ),
                preparation_time = 56,
                weight = 1.337,
                selected_shipping_data = {
                    'key' : null
                    },
                reference_code = '',
                promotion_discount_amount = 1.337,
                promotion_data = {
                    'key' : null
                    },
                digipay_markup_amount = 56,
                markup_commission_percentage = 56,
                previous_status = 1,
                previous_status_display = '',
        )
        """

    def testOrderDetail(self):
        """Test OrderDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
